### ISSUE TITLE
Error on start (2.7.18-fc)

### ISSUE THREAD

**Issue by XaviP** [faircoin/electrumfair#6]
Branch 2.7.18-fc is giving error on start:
```
Traceback (most recent call last):
  File "/usr/local/bin/electrumfair", line 5, in <module>
    pkg_resources.run_script('ElectrumFair==2.7.18', 'electrumfair')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ElectrumFair-2.7.18-py2.7.egg/EGG-INFO/scripts/electrumfair", line 98, in <module>
    from electrumfair import bitcoin, network
  File "/usr/local/lib/python2.7/dist-packages/ElectrumFair-2.7.18-py2.7.egg/electrumfair/__init__.py", line 3, in <module>
    from wallet import Synchronizer, WalletStorage, Wallet, Imported_Wallet
  File "/usr/local/lib/python2.7/dist-packages/ElectrumFair-2.7.18-py2.7.egg/electrumfair/wallet.py", line 63, in <module>
    import paymentrequest
  File "/usr/local/lib/python2.7/dist-packages/ElectrumFair-2.7.18-py2.7.egg/electrumfair/paymentrequest.py", line 39, in <module>
    import paymentrequest_pb2 as pb2
  File "/usr/local/lib/python2.7/dist-packages/ElectrumFair-2.7.18-py2.7.egg/electrumfair/paymentrequest_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x14paymentrequest.proto\x12\x08payments\"+\n\x06Output\x12\x11\n\x06\x61mount\x18\x01 \x01(\x04:\x01\x30\x12\x0e\n\x06script\x18\x02 \x02(\x0c\"\xa3\x01\n\x0ePaymentDetails\x12\x15\n\x07network\x18\x01 \x01(\t:\x04main\x12!\n\x07outputs\x18\x02 \x03(\x0b\x32\x10.payments.Output\x12\x0c\n\x04time\x18\x03 \x02(\x04\x12\x0f\n\x07\x65xpires\x18\x04 \x01(\x04\x12\x0c\n\x04memo\x18\x05 \x01(\t\x12\x13\n\x0bpayment_url\x18\x06 \x01(\t\x12\x15\n\rmerchant_data\x18\x07 \x01(\x0c\"\x95\x01\n\x0ePaymentRequest\x12\"\n\x17payment_details_version\x18\x01 \x01(\r:\x01\x31\x12\x16\n\x08pki_type\x18\x02 \x01(\t:\x04none\x12\x10\n\x08pki_data\x18\x03 \x01(\x0c\x12\"\n\x1aserialized_payment_details\x18\x04 \x02(\x0c\x12\x11\n\tsignature\x18\x05 \x01(\x0c\"\'\n\x10X509Certificates\x12\x13\n\x0b\x63\x65rtificate\x18\x01 \x03(\x0c\"i\n\x07Payment\x12\x15\n\rmerchant_data\x18\x01 \x01(\x0c\x12\x14\n\x0ctransactions\x18\x02 \x03(\x0c\x12#\n\trefund_to\x18\x03 \x03(\x0b\x32\x10.payments.Output\x12\x0c\n\x04memo\x18\x04 \x01(\t\">\n\nPaymentACK\x12\"\n\x07payment\x18\x01 \x02(\x0b\x32\x11.payments.Payment\x12\x0c\n\x04memo\x18\x02 \x01(\tB(\n\x1eorg.bitcoin.protocols.paymentsB\x06Protos')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```
On machine:
```
$ uname -a
Linux 3.13.0-123-generic #172-Ubuntu SMP Mon Jun 26 18:04:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by XaviP** [comment]
Solved with new version. Thanks. Closing.
